### PR TITLE
Fix three small typos

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by will-murphy** [comment]
Thanks Alex! Feel free to keep contributing. If you want to take on a more active role, feel free to reach out.

**Comment by AlexKnauth** [comment]
Has the website been updated?

**Comment by AlexKnauth** [comment]
@will-murphy I'm still seeing these typos on the website. Has it been updated since?

**Comment by will-murphy** [comment]
I apologize for the delay. The website is up to date.

**Pull request merged**
